# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('school', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('code', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('wordpressTag', models.CharField(max_length=120)),
                ('parentPaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Newspaper.Paper')),
            ],
        ),
    ]
