# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Newspaper', '0002_auto_20180530_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parentPaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Newspaper.Paper'),
        ),
    ]
